### PR TITLE
feat: customize ui

### PR DESCRIPTION
**Pull request by bunnybunbun37204**
add customize ui with new lib
    "@nanostores/react": "^0.7.1",
    "nanostores": "^0.9.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.4.1"

### CODE REVIEW

**Review by betich — CHANGES_REQUESTED** [review]
are you using the styles here? would be a better idea to style everything using the same system (tailwind)

**Comment by betich** [comment]
otherwise lgtm

**Comment by bunnybunbun37204** [comment]
> are you using the styles here? would be a better idea to style everything using the same system (tailwind)

do u mean style in     `<link rel="stylesheet" href="global.css">` in **BaseLayout.astro** right ?, I cant find the googlefont or fontsource for these fonts, so i used global.css to import fonts from my local storage

**Comment by bunnybunbun37204** [comment]
> > are you using the styles here? would be a better idea to style everything using the same system (tailwind)
> 
> do u mean style in `<link rel="stylesheet" href="global.css">` in **BaseLayout.astro** right ?, I cant find the googlefont or fontsource for these fonts, so i used global.css to import fonts from my local storage
Do you have a better idea ;-;

**Comment by bunnybunbun37204** [comment]
> are you using the styles here? would be a better idea to style everything using the same system (tailwind)

Do u have a better idea ;-;

**Comment by betich** [comment]
actually i meant just the default styles in the `Layout.astro` file. but i see it has now been removed

**Comment by betich** [comment]
the font source for LINE Seed Sans TH can be found [here](https://seed.line.me/index_th.html)

**Comment by betich** [comment]
resolved the merge conflict, don't forget to install the dependencies

**Comment by betich** [comment]
i removed `package-lock.json`, please use [pnpm](https://pnpm.io/) as the package manager

**Comment by betich** [comment]
added typescript types by running the command `pnpm astro add react`

**Pull request merged**
